# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

# Issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š

defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "feature_request.yml"
    name: "ğŸ’¡ æ”¹å–„ãƒ»ãƒªãƒ•ã‚¡ã‚¯ã‚¿ãƒªãƒ³ã‚°"
    about: "æ”¹å–„ãƒ»ãƒªãƒ•ã‚¡ã‚¯ã‚¿ãƒªãƒ³ã‚°ã‚’ææ¡ˆã™ã‚‹"
